services:
  web:
    container_name: personal-portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3888:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: always
    command: nginx -g 'daemon off;'